### ISSUE TITLE
Auto GC not working as expected 

### ISSUE THREAD

**Issue by apetta** [ipfs-shipyard/go-ipfs-docker-examples#4]
Hi,

Thanks for putting up this repo, it's very helpful for understanding how to customise the kubo docker instance. One thing I'm struggling with is getting the `Datastore.GCPeriod` to kick in. The `Datastore.StorageGCWatermark` seems to be working properly, but the timed garbage collection is not working as expected. My understanding for the latter is that GC would happen every X seconds/minutes (whatever is set in the config).

Would appreciate your thoughts as to what might be going wrong, or if I have misinterpreted how `Datastore.GCPeriod` is supposed to work.

Sharing my settings below.

**ipfs-config.sh**
```
#!/bin/sh
echo "setting garbage collection params"
ipfs config --json Datastore.StorageMax '"12Mb"'
ipfs config --json Datastore.StorageGCWatermark '75'
ipfs config --json Datastore.GCPeriod '"5s"'
```

**dockerfile**
```
FROM ipfs/kubo:latest

ADD ipfs-config.sh /container-init.d/ipfs-config.sh
RUN chmod a+x /container-init.d/ipfs-config.sh

EXPOSE 8080

CMD ["daemon", "--migrate=true", "--agent-version-suffix=docker", "--enable-gc=true"]
```

**docker-compose.yaml**
```
version: "3.9"
services:
  ipfs_host:
    build: .

    ports:
      - "127.0.0.1:8080:8080"

    environment:
      - IPFS_PROFILE=server

    volumes:
      - ipfs_data:/data/ipfs

    platform: linux/amd64 # optional, defaults to linux/amd64

volumes:
  ipfs_data:
```

Thanks!!
